baseURL = ""
languageCode = "en-us"
title = "Hannah Luebbering"
theme = "hugo-devresume-theme"
enableGitInfo = true


[params]
    author = "hannahluebbering"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"
    primaryColor = "#ec5b95"
    textPrimaryColor = "#292929"
    


    [params.profile]
        enable = true
        name = "Hannah Luebbering"
        tagline = "Applied Mathematics and Computer Science"
        avatar = "avatar.png"



    [params.contact]
        enable = true
        location = "North Carolina"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "luebhr@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "//hannah-luebbering.com"
        text = "Homepage"
        [[params.contact.list]]
        icon = "fas fa-laptop-code"
        url = "//dmds.lucymcgowan.com/people/"
        text = "DM Data Science Lab"



    [params.skills]
        enable = true

        [[params.skills.list]]
        [[params.skills.list.items]]
        details = "Web Design using HTML and CSS"
        [[params.skills.list.items]]
        details = "Strong math skills"
        [[params.skills.list.items]]
        details = "Research and Technology"
        [[params.skills.list.items]]
        details = "Data Processing"
        [[params.skills.list.items]]
        details = "Complex problem solving skills"
        [[params.skills.list.items]]
        details = "Teamwork"


        [[params.skills.list]]
        title = "Programming Languages"
        [[params.skills.list.items]]
        details = "R"
        [[params.skills.list.items]]
        details = "MatLab"
        [[params.skills.list.items]]
        details = "JavaScript"
        [[params.skills.list.items]]
        details = "LaTex"



    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS Applied Mathematics"
        university = "Wake Forest University"
        dates = "2017 - 2021"
        [[params.education.list]]
        degree = "Blue Valley North High School"
        university = "Varsity Cross Country, Cross Country Team Captain, Varsity Track, National Honor Society, Science National Honor Society"
        dates = "2013 - 2017"
        
    [params.awards]
        enable = false
        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"



    [params.languages]
        enable = false
        [[params.languages.list]]
        name = "English"
        level = "Native"


    [params.interests]
        enable = true
        [[params.interests.list]]
        name = "Running"
        [[params.interests.list]]
        name = "Skiing"
        [[params.interests.list]]
        name = "Web Design"
        [[params.interests.list]]
        name = "Architecture"
        [[params.interests.list]]
        name = "Photography"
        


    [params.summary]
        enable = true
        text = "Applied Mathematics and Computer Science student at Wake Forest University seeks a career in software computing, data science, and related technologies. Motivated to learn, grow and excel in technology."





    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Association for Women in Mathematics Executive Committee"
        dates = "2020 - Present"
        company = "Wake Forest University"
        [[params.experience.list.items]]
        details = "Led and participated in various programs and workshops to mentor students in math and science"
        

        [[params.experience.list]]
        title = "Data Science Pedagogy Research"
        dates = "2020 - Present"
        company = "Wake Forest University"
        [[params.experience.list.items]]
        details = "Worked with Dr. McGowan, Professor in Statistics at Wake Forest University"
        [[params.experience.list.items]]
        details = "Studied learn-R package and built various tutorials published on GitHub"
        [[params.experience.list.items]]
        details = "Tutorials explained various R packages such as tidy data, types of data frames, manipulating data frames in R using tidyverse, and more"
    
        
        
        [[params.experience.list]]
        title = "New South Wales Health Internship/Research Project Assistant"
        dates = "2019 - 2020"
        company = "Westmead Institute For Medical Research Sydney, New South Wales"
        [[params.experience.list.items]]
        details = "Completed projects with various industries involving preventative health, chronic illness, immersive technology, precision medicine, open data, and more"
        [[params.experience.list.items]]
        details = "Conducted thorough research using diverse resources to assist professional staff with project tasks"

        [[params.experience.list]]
        title = "Nanotechnology and Chemistry Research"
        dates = "2018 - 2020"
        company = "Wake Forest University"
        [[params.experience.list.items]]
        details = "Worked with Dr. Ghadiri in the Chemistry Department."
        [[params.experience.list.items]]
        details = "Conducted experiments and analyzed samples using UV-VIS spectroscopy, confocal microscopy, and Agilent software"
        [[params.experience.list.items]]
        details = "Tracked experimental results and analyzed data using MatLab and Excel"

        [[params.experience.list]]
        title = "Concussion Research Assistant"
        dates = "2018 - 2020"
        company = "Wake Forest University"
        [[params.experience.list.items]]
        details = "Monitored soccer players, outfitted players with mouthpiece software, collected data, and analyzed data for study of head impact in sports and injury biomechanics"
        
        [[params.experience.list]]
        title = "Clinical Internship/Shadowing Program"
        dates = "2018 - 2019"
        company = "Wake Forest Baptist Health"
        [[params.experience.list.items]]
        details = "Shadowed Dr. Talbott, an anesthesiologist at Wake Forest Baptist Health"
        [[params.experience.list.items]]
        details = "Gained high quality clinical experience and increased understanding of the practice of medicine"


    



    [params.projects]
        enable = true
        
        [[params.projects.list]]
        title = "Kappa Kappa Gamma Sorority"
        tagline = "Recruitment counselor and advisor for recruits and freshmen"

        [[params.projects.list]]
        title = "Sydney: Math and Computer Science Abroad"
        tagline = "Attended University of Sydney for five months to study advanced mathematics and computer science courses"

        [[params.projects.list]]
        title = "London: Organic Chemistry II Abroad"
        tagline = "Traveled to London with Wake Forest professor and students to study Organic Chemistry II"
        
        [[params.projects.list]]
        title = "Children's Mercy Hospital Volunteer"
        tagline = "Volunteered at the Children's Mercy Hospital as a Pathfinder. Helped patients and families navigate the hospital and assisted nurses in the sports medicine clinic."
        
        [[params.projects.list]]
        title = "UCLA Student Volunteer"
        tagline = "Volunteered at UCLA and around Los Angeles and earned 45 of community service hours. Provided meals and other assistance to families, schools, and underprivileged residents of Los Angeles."

        
    [params.information]
        enable = true
        
        [[params.information.list]]
        
        [[params.information.list.items]]
        details = "Association for Women in Mathematics"
        [[params.information.list.items]]
        details = "Kappa Kappa Gamma Sorority"
        [[params.information.list.items]]
        details = "Women in Computer Science"
        [[params.information.list.items]]
        details = "Kansas City Running Club"
        
    

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/hluebbering"
        title = "hluebbering"
        [[params.social.list]]
        icon = "fas fa-bookmark"
        url = "//dmds.lucymcgowan.com/people/"
        title = "hluebbering"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//www.linkedin.com/in/hannah-luebbering-99609818a/"
        title = "hannah-luebbering"
        [[params.social.list]]
        icon = "fas fa-camera"
        url = "//vsco.co/hannahluebbering/gallery"
        title = "@hannahluebbering"


