baseURL = ""
languageCode = "en-us"
title = "Hannah Luebbering"
theme = "hugo-devresume-theme"
enableGitInfo = true

[params]
    author = "hannahluebbering"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"
    primaryColor = "#ec5b95"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Hannah Luebbering"
        tagline = "Applied Mathematics and Computer Science"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "North Carolina"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "luebhr@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://www.hannah-luebbering.com"
        text = "hannah-luebbering.com"


    [params.skills]
        enable = true
        [[params.skills.list]]
        [[params.skills.list.items]]
        details = "Graphing and Visualizations"
        [[params.skills.list.items]]
        details = "Visualizing Data with Tableau"
        [[params.skills.list.items]]
        details = "Mathematical Modeling"
        [[params.skills.list.items]]
        details = "Research and Technology"
        [[params.skills.list.items]]
        details = "Statistical Analysis"

        #[[params.skills.list]]
        #title = "Programming Languages"
        [[params.skills.list.items]]
        details = "R"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "Java"
        [[params.skills.list.items]]
        details = "SQL"
        [[params.skills.list.items]]
        details = "MatLab"
        [[params.skills.list.items]]
        details = "SAS"
        

    [params.education]
        enable = true
        [[params.education.list]]
        degree = "BS in Applied Mathematics, Minor in Computer Science"
        university = "Wake Forest University"
        location = "Winston Salem, NC | 2017 - 2021"
        gpa = "GPA: 3.471"
        [[params.education.list.items]]
        details = "Association for Women in Mathematics"
        [[params.education.list.items]]
        details = "Women in Computer Science"
        [[params.education.list.items]]
        details = "Kappa Kappa Gamma Sorority"
        #[[params.education.list.items]]
        #details= "Excelled in machine learning and data science coursework.

        [[params.education.list]]
        degree = "Study Abroad, Mathematics and Computer Science"
        university = "University of Sydney"
        location = "Sydney, Australia | 2019"
        [[params.education.list.items]]
        details = "SUMS, Mathematics Society"

        [[params.education.list]]
        degree = "Study Abroad, Organic Chemistry"
        university = "Queen Mary University"
        dates = "London, England | 2018"
        
        [[params.education.list]]
        university = "Blue Valley North"
        degree = "High School Diploma"
        dates = "Overland Park, KS | 2013 - 2017"
        [[params.education.list.items]]
        details = "Varsity Cross Country and Track"
        [[params.education.list.items]]
        details = "Cross Country Team Captain"
        [[params.education.list.items]]
        details = "National Honor Society"
        [[params.education.list.items]]
        details = "Science National Honor Society"
  
    [params.languages]
        enable = false
        [[params.languages.list]]
        name = "English"
        level = "Native"

    ## PUBLIFICATIONS
    [params.interests]
        enable = true
        [[params.interests.list]]
        name = "Pump-Probe Microscopic Imaging of Solution Processed Cu2BaSnS4-xSex thin films; stable charge carrier."
        #date = "2021"
        date = "Hannah Luebbering, Ashkan Shafiee, Betul Teymur, Yongshin Kim, David B. Mitzi, Elham Ghadiri | 2021"
        

    
    [params.awards]
        enable = true
        [[params.awards.list]]
        name = "IT Automation with Python"
        body = "Google Professional Certificate"
        [[params.awards.list]]
        name = "AWS Fundamentals: Going Cloud-Native"
        body = "Amazon Web Services"
        
    [params.summary]
        enable = true
        #text = "Applied Mathematics and Computer Science student at Wake Forest University seeking a full or part-time position in advance of attending graduate school. A dedicated, hardworking student, eager to accept new challenges, and always strives to keep learning. Motivated to learn, grow, and excel in data analysis, mathematics, and science-related fields. Proven success working in fast-paced and collaborative settings."
        text = "Applied Mathematics and Computer Science student at Wake Forest University seeking a full or part-time position in advance of attending graduate school. Motivated to learn, grow, and excel in data analysis, mathematics, and science-related fields. Proven success working in challenging, fast-paced, and collaborative settings."

    [params.experience]
        enable = true
        [[params.experience.list]]
        title = "Data Science Pedagogy Research"
        dates = "2020 - Present"
        company = "Wake Forest University"
        [[params.experience.list.items]]
        details = "Worked with Dr. McGowan in the Department of Mathematics & Statistics at Wake Forest University."
        [[params.experience.list.items]]
        details = "Studied learn-R package and built various tutorials published on GitHub."
        [[params.experience.list.items]]
        details = "Tutorials explained various R packages such as tidy data, types of data frames, manipulating data frames in R using tidyverse, and more."
    
        
        [[params.experience.list]]
        title = "New South Wales Health Internship/Research Project Assistant"
        dates = "2019"
        company = "Westmead Institute For Medical Research Sydney, New South Wales"
        [[params.experience.list.items]]
        details = "Completed projects with various industries involving preventative health, chronic illness, immersive technology, precision medicine, open data, and more."
        [[params.experience.list.items]]
        details = "Conducted thorough research using diverse resources to assist professional staff with project tasks."

        [[params.experience.list]]
        title = "Nanotechnology and Chemistry Research"
        dates = "2018 - 2019"
        company = "Wake Forest University"
        [[params.experience.list.items]]
        details = "Worked with Dr. Ghadiri in the Department of Chemistry at Wake Forest University."
        [[params.experience.list.items]]
        details = "Conducted experiments and analyzed samples using UV-VIS spectroscopy, confocal microscopy, and Agilent software."
        [[params.experience.list.items]]
        details = "Tracked experimental results and analyzed data using MatLab and Excel."
        #[[params.experience.list.items]]
        #details = "Listed as the first author of the journal publication."
        
        [[params.experience.list]]
        title = "Concussion Research Assistant"
        dates = "2018"
        company = "Wake Forest Innovation Quarter"
        [[params.experience.list.items]]
        details = "Monitored soccer players, outfitted players with mouthpiece software, collected data, and analyzed data for study of head impact in sports and injury biomechanics."
        
        [[params.experience.list]]
        title = "Clinical Internship and Shadowing Program"
        dates = "2018"
        company = "Wake Forest Baptist Health"
        [[params.experience.list.items]]
        details = "Shadowed Dr. Talbott, an anesthesiologist at Wake Forest Baptist Health."
        [[params.experience.list.items]]
        details = "Gained high quality clinical experience and increased understanding of the practice of medicine."
        
        [[params.experience.list]]
        title = "Orthopaedic Surgery Shadow"
        dates = "2017"
        company = "KC Orthopaedic Institute"
        [[params.experience.list.items]]
        details = "Shadowed several orthopaedic doctors during surgeries and patient office visits."
        [[params.experience.list.items]]
        details = "Shadowed Dr. Steven Joyce for knee arthroscopy and rotator cuff tear repair surgeries, Dr. Dan Gurba for total knee replacements, Dr. Kirk McCullough for ankle reconstruction surgeries, and Dr. JP Halloran for ACL repairs and ankle reconstructions."


    [params.projects]
        enable = true
        [[params.projects.list]]
        title = "Intensive Care Unit Volunteer"
        company = "Wake Forest Baptist Health"
        dates = "2017 - 2018"
        [[params.projects.list.items]]
        details = "Volunteered at the Wake Forest Baptist Medical Center in the Intensive Care Unit." 
        [[params.projects.list.items]]
        details = "Worked at the front desk, assisted nurses, helped patients, and answered phone calls."
        
        [[params.projects.list]]
        title = "Children's Mercy Hospital Volunteer Internship"
        company = "Children's Mercy Hospital"
        dates = "2015 - 2016"
        [[params.projects.list.items]]
        details = "Volunteered at the Children's Mercy Hospital as a Pathfinder."
        [[params.projects.list.items]]
        details = "Helped patients and families navigate the hospital and assisted nurses in the sports medicine clinic."
        
        [[params.projects.list]]
        title = "UCLA Student Volunteer"
        company = "University of California, Los Angeles"
        dates = "2015"
        [[params.projects.list.items]]
        details = "Volunteered around Los Angeles and earned 45 community service hours." 
        [[params.projects.list.items]]
        details = "Provided meals and other assistance to families, schools, and underprivileged residents of Los Angeles."

       
    [params.information]
        enable = true
        [[params.information.list]]
        title = "Association for Women in Mathematics Executive Committee"
        dates = "2019 - 2021"
        company = "Wake Forest University"
        [[params.information.list.items]]
        details = "Led and participated in various programs and workshops to mentor students in math and science."
       

       
    [params.social]
        enable = true
        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/hluebbering"
        title = "hluebbering"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//www.linkedin.com/in/hannah-luebbering-99609818a/"
        title = "hannah-luebbering"
        [[params.social.list]]
        icon = "fas fa-laptop-code"
        url = "https://dmds.lucymcgowan.com/authors/hannah-luebbering/"
        title = "DM Data Science Lab"
        